name: quickdrop_sellers
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.5

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_storage: ^12.3.6
  firebase_auth: ^5.3.3
  firebase_core: ^3.9.0
  flutter_svg: ^2.0.16
  flutter_bloc: ^8.1.6
  cloud_firestore: ^5.6.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  go_router: ^14.6.1
  intl: ^0.19.0
  toastification: ^2.3.0
  lottie: ^3.1.3
  cached_network_image: ^3.3.1
  rxdart: ^0.27.7
  firebase_analytics: ^11.3.6
  extensions: 
    git: 
      url: https://github.com/4CROS2/string_extensions.git 
      ref: main
  custom_dropdown_menu:
    git:
      url: https://github.com/4CROS2/custom-dropdown-menu.git
      ref: main


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_code_metrics: null


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/lotties/wellcome/
  fonts:
    - family: Questrial
      fonts:
        - asset: assets/fonts/questrial.ttf
    - family: Redhat
      fonts:
        - asset: assets/fonts/redhat_bold.ttf
          weight: 700
        - asset: assets/fonts/redhat_semi.ttf
          weight: 500
        - asset: assets/fonts/redhat_regular.ttf
