name: quickdrop_sellers
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_storage: ^12.3.5
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  flutter_svg: ^2.0.14
  flutter_bloc: ^8.1.6
  cloud_firestore: ^5.4.5
  get_it: ^8.0.2
  go_router: ^14.6.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  generate: true
  uses-material-design: true