name: Flutter CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: "Static code analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2

      - name: Setup Java
        uses: actions/setup-java@v3.4.1
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            $PUB_CACHE
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Get dependencies
        run: flutter pub get

      - name: Lint analysis
        run: flutter analyze

  check-dart-formatting:
    name: "Check Dart formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.6.2

      - name: Check Dart formatting
        id: format
        run: |
          dart format --set-exit-if-changed .
          if [ $? -ne 0 ]; then
            echo "Code needs formatting. Formatting and committing changes."
            dart format .
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git commit -am "Auto-formatted code"
            git push